Repository Workiva/react_testing_library, pull requests merged in 2021-11, with the labels that each got.

#38 Misc maintenance
  README.md
  example/README.md
  pubspec.next.yaml
  pubspec.yaml
  test/unit/unit_test_template.html
Labels: semver: Patch, Merge Requirements Met, RM Ready

#41 Align waitFor implementation more closely with JS implementation
  lib/src/dom/async/wait_for.dart
  test/unit/dom/wait_for_test.dart
Labels: Merge Requirements Unmet

#40 Handle synchronous TestFailure within async fn body
  lib/src/dom/async/wait_for.dart
  test/unit/dom/wait_for_test.dart
Labels: enhancement, semver: Major, Merge Requirements Met, RM Ready

#39 CPLAT-15989: Surface Event Handler Errors
  lib/src/dom/fire_event.dart
  lib/src/user_event/user_event.dart
  lib/src/util/event_handler_error_catcher.dart
  test/unit/dom/fire_event_test.dart
  test/unit/user_event/clear_test.dart
  test/unit/user_event/click_test.dart
  test/unit/user_event/hover_test.dart
  test/unit/user_event/paste_test.dart
  test/unit/user_event/select_options_test.dart
  test/unit/user_event/tab_test.dart
  test/unit/user_event/type_test.dart
  test/unit/user_event/upload_test.dart
  test/unit/util/event_handler_error.dart
Labels: semver: Major, Merge Requirements Met, RM Ready

#42 Add 2.0.0 changelog entry
  CHANGELOG.md
Labels: semver: Patch, Merge Requirements Met, RM Ready

#43 Update test_html_builder to v2
  pubspec.yaml
Labels: semver: Patch, Merge Requirements Met, RM Ready
