Repository Workiva/react_testing_library, pull requests merged in 2021-09, with the labels that each got.

#29 Fix typing in README example
  README.md
  test/unit/dom/matchers/has_form_values_test.dart
  test/unit/dom/matchers/is_partially_checked_test.dart
Labels: Merge Requirements Met, RM Ready

#30 dart 2.13
  .github/workflows/dart_ci.yml
  Dockerfile
Labels: Merge Requirements Met, RM Ready

#31 CPLAT-15554 Fix render swallowing errors on component mount
  CHANGELOG.md
  lib/src/dom/accessibility_helpers.dart
  lib/src/dom/within.dart
  lib/src/react/render/render.dart
  lib/src/util/console_log_utils.dart
  test/unit/console_log_utils_test.dart
  test/unit/dom/accessibility_helpers_test.dart
  test/unit/dom/wait_for_test.dart
  test/unit/dom/within_test.dart
  test/unit/react/render_test.dart
  test/unit/util/exception.dart
  test/unit/util/prints_and_logs_recording.dart
Labels: semver: Patch, Merge Requirements Met, RM Ready

#32 CPLAT-15593 Fix printConsoleLogs state error
  CHANGELOG.md
  lib/src/util/console_log_utils.dart
  test/unit/console_log_utils_test.dart
Labels: semver: Patch, Merge Requirements Met, RM Ready

#33 Raise the Dart SDK minimum to at least 2.11.0
  .github/workflows/dart_ci.yml
  pubspec.yaml
  test/unit/dom/matchers/has_form_values_test.dart
  test/unit/dom/matchers/is_partially_checked_test.dart
  test/unit/util/exception.dart
  test/unit/util/prints_and_logs_recording.dart
Labels: Merge Requirements Unmet, RM Ready

#36 Only check formatting in CI on Dart 2.13.4
  .github/workflows/dart_ci.yml
  CHANGELOG.md
Labels: semver: Patch, Merge Requirements Met, RM Ready
